In [ ]:
# from google.colab import drive
# # drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# drive.flush_and_unmount()

In [ ]:
# !umount /content/drive

umount: /content/drive: target is busy.

In [ ]:
# import os

In [ ]:
# os.getcwd()

OSError: [Errno 107] Transport endpoint is not connected

#### Downloading CallGraph_0.csv

In [ ]:

# file_id = '1l1Zebe2-r6DrL1PwbNB431RCscSu9IXz' # Replace with the actual file ID
# !gdown --id $file_id

#### Downloading MCRRT.csv

In [ ]:

# file_id = '1ynXM49k1FdyzhfrFPxnZI4_HXO8k58cy' # Replace with the actual file ID
# !gdown --id $file_id

#### Downloading MSMetrics.csv

In [ ]:
# file_id = '1sZutUdbaWdmD3DqaNW-Zv6kjPSXD17tZ' # Replace with the actual file ID
# !gdown --id $file_id

#### Downloading NodeMetrics.csv

In [ ]:
# file_id = '1k7w6pgM9GL6F78LzBf_jgVU-i500nIkV' # Replace with the actual file ID
# !gdown --id $file_id

### Checking Directory

In [1]:
import os
os.listdir()

['.git',
 '.venv',
 '.~lock.CallGraph_350k.csv#',
 'Alibaba_Data_Job_Level.csv',
 'Alibaba_Data_Task_Level.csv',
 'batch_instance.csv',
 'batch_task.csv',
 'CallGraph_0.csv',
 'CallGraph_350k.csv',
 'container_event.csv',
 'container_usage.csv',
 'Filtered_mc_rrt.csv',
 'Filtered_MSMetrics.csv',
 'Filtered_NodeMetric.csv',
 'MCRRTUpdate_0.csv',
 'MSMetricsUpdate_0.csv',
 'NodeMetricsUpdate_0.csv',
 'server_event.csv',
 'server_usage.csv',
 'SoCC2021.pdf',
 'ssp.ipynb']

### Required Modules

In [2]:
import pandas as pd

### Reading all .CSV Files
##### 1. MicroService_Metrics ---> ms_metric
##### 2. MC_RRT ---> mc_rrt
##### 3. Node Metrics ---> node_metric
##### 4. CallGraph --> callgraph

In [3]:
ms_metric = pd.read_csv('MSMetricsUpdate_0.csv',on_bad_lines='skip')

In [4]:
mc_rrt = pd.read_csv('MCRRTUpdate_0.csv',on_bad_lines='skip')

In [5]:
node_metric = pd.read_csv('NodeMetricsUpdate_0.csv',on_bad_lines='skip')

In [6]:
call_graph = pd.read_csv('CallGraph_0.csv',on_bad_lines='skip')

In [7]:
try:
    callp = call_graph
    nodem = node_metric
    msmetric = ms_metric
    mcrrt = mc_rrt
except: 
    raise Exception("Error")

In [8]:
print(callp.shape,'\n',
msmetric.shape,'\n',
mcrrt.shape)

(13331267, 11)
 (13987704, 6)
 (14897854, 22)

### CallGraph Table – Column Description

👉 This dataset from Alibaba Group represents microservice-to-microservice interactions (call relationships).

🔹 Basic Information
1. timestamp

Time when the call occurred

Unit: milliseconds

2. traceid

Unique ID of a request

All rows with same traceid belong to one request flow

Used to reconstruct full call chain

3. service

High-level business service ID

Represents application-level functionality

4. rpc_id

Defines call hierarchy (parent-child relationship)

Example:

0 → root call

0.1 → child call

0.1.1 → deeper level

5. rpctype

Type of communication between services

Values:

rpc → remote call

db → database call

mc → cache call

http → HTTP request

🔗 Microservice Interaction
6. um (Upstream Microservice)

The caller service

Initiates the request

7. uminstanceid

Specific instance (container) of the caller service

8. interface

API or endpoint used for the call

Identifies which function is invoked

9. dm (Downstream Microservice)

The callee service

Receives and processes the request

10. dminstanceid

Specific instance (container) of the callee service

⏱️ Performance
11. rt (Response Time)

Time taken for the call to complete

Unit: millisecond

In [9]:
set(callp['rpctype'].to_list())

{'UNKNOWN', 'db', 'http', 'mc', 'mq', 'rpc'}

In [10]:
callp['rpctype'].nunique()

6

In [11]:
callp.head(5)

,timestamp,traceid,service,rpc_id,rpctype,um,uminstanceid,interface,dm,dminstanceid,rt
0,115352,T_11560863075,S_153587416,0.1,rpc,MS_58845,MS_58845_POD_0,xOuy6-80Vt,MS_71712,MS_71712_POD_244,2.0
1,86450,T_22121589080,S_1798353,0.1,rpc,MS_24094,MS_24094_POD_3317,4Db39LxDTC,MS_24094,MS_24094_POD_5168,5.0
2,86450,T_22121589080,S_1798353,0.1,rpc,MS_24094,MS_24094_POD_983,4Db39LxDTC,MS_24094,MS_24094_POD_5168,5.0
3,155753,T_22121586395,S_85905920,0.1,rpc,MS_24094,MS_24094_POD_5463,1oNt-EK5Lm,MS_67455,MS_67455_POD_222,9.0
4,90649,T_22825688569,S_160146479,0.1.1.1,http,MS_29868,MS_29868_POD_22,XQrDXTN_dB,UNKNOWN,UNKNOWN,18.0

### Node Metric Table Description

1. timestamp

Time when the metrics were recorded

Unit: milliseconds

Data is recorded at regular intervals (typically every 60 seconds)

2. nodeid

Unique identifier of a bare-metal node (physical server)

Example: NODE_10632

👉 Meaning:

Represents a machine in the cluster

Multiple microservice containers run on one node

⚙️ Resource Utilization
3. cpu_utilization

CPU usage of the node

Normalized value between 0 and 1

👉 Interpretation:

Value	Meaning
0.0	No CPU usage
0.5	Moderate usage
1.0	Fully utilized CPU
4. memory_utilization

Memory (RAM) usage of the node

Normalized value between 0 and 1

👉 Interpretation:

Value	Meaning
0.2	Low memory usage
0.7	High usage
1.0	Fully utilized memory

In [12]:
node_metric.head(5)

   timestamp      nodeid  cpu_utilization  memory_utilization
0   33240000  NODE_23547         0.116474            0.462065
1   33240000  NODE_22287         0.345439            0.278756
2   33240000  NODE_21472         0.370310            0.223923
3   33240000  NODE_21294         0.144132            0.209197
4   33240000  NODE_20794         0.288578            0.147916

In [13]:
node_metric['nodeid'].nunique()

43253

### MSMetric Table
1. timestamp

Time when metrics were recorded

Interval: every 60 seconds

Unit: milliseconds

2. msname

Name of the microservice

Logical service identifier

Used to join with CallGraph

3. msinstanceid

Unique ID of a microservice instance (container)

One service can have multiple instances

4. nodeid

ID of the physical machine (bare-metal node)

Indicates where the service instance is running

⚙️ Resource Utilization
5. cpu_utilization

CPU usage of the microservice instance

Normalized value (0 to 1)

👉 Interpretation:

0 → no usage

1 → full CPU utilization

6. memory_utilization

Memory usage of the microservice instance

Normalized value (0 to 1)

👉 Interpretation:

0 → no usage

1 → full memory utilization

In [14]:
msmetric.head(5)

,timestamp,msname,msinstanceid,nodeid,cpu_utilization,memory_utilization
0,300000,MS_68185,MS_68185_POD_91,NODE_20236,0.172378,0.662361
1,420000,MS_25215,MS_25215_POD_372,NODE_36528,0.085708,0.432862
2,720000,MS_31285,MS_31285_POD_916,NODE_23966,0.445229,0.572093
3,780000,MS_42019,MS_42019_POD_38,NODE_34880,0.091057,0.529339
4,900000,MS_9482,MS_9482_POD_332,NODE_45529,0.177660,0.642626

#### MCRRT Table Details 
timestamp : Time of Measurement in milliseconds
1. timestamp
Time when the metrics were recorded
Unit: milliseconds
Recorded every 60 seconds
2. msname
Name of the microservice
Represents the logical service
Used to join with CallGraph (um, dm)
3. msinstanceid
Unique ID of a microservice instance (container)
One service can have multiple instances
4. nodeid
ID of the physical machine (bare-metal node)
Indicates where the container is running
🔥 RPC (Remote Procedure Call)
👉 Provider Side (Service being called)
5. providerrpc_rt
Average response time when this service is called by others
Unit: milliseconds
6. providerrpc_mcr
Call rate of incoming RPC requests
Shows how frequently other services call this service
Normalized value (0–1)
7. consumerrpc_rt
Average response time of outgoing RPC calls made by this service
8. consumerrpc_mcr
Frequency of outgoing RPC calls made by this service
Normalized (0–1)
9. writemc_rt
Time taken to write data into cache
10. writemc_mcr
Frequency of cache write operations
11. readmc_rt
Time taken to read data from cache
12. readmc_mcr
🗄️ Database Operations (DB)
13. writedb_rt
Time taken to write data into database
14. writedb_mcr
Frequency of database write operations
15. readdb_rt
Time taken to read data from database
16. readdb_mcr
Frequency of database read operations
17. consumermq_rt
Time taken to consume (receive) messages from queue
18. consumermq_mcr
Frequency of consuming messages from queue
19. providermq_rt
Time taken to send messages to queue
20. providermq_mcr
Frequency of sending messages to queue

21. http_mcr
Frequency of HTTP requests made or received

22. http_rt

Response time of HTTP requests

In [15]:
mcrrt.head(5)

,timestamp,msname,msinstanceid,nodeid,providerrpc_rt,providerrpc_mcr,consumerrpc_rt,consumerrpc_mcr,writemc_rt,writemc_mcr,...,writedb_rt,writedb_mcr,readdb_rt,readdb_mcr,consumermq_rt,consumermq_mcr,providermq_rt,providermq_mcr,http_mcr,http_rt
0,60000,MS_49464,MS_49464_POD_4,NODE_41256,0.000000,0.000000,5.346655,0.000000e+00,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,4.96123,0.000155,1.344713,0.000071,1.865916e-07,0.083333
1,120000,MS_66860,MS_43316_POD_3,NODE_36486,6.257353,0.000001,0.000000,7.869866e-13,0.0,0.0,...,1.911765,0.000002,0.442857,0.000002,0.00000,0.000000,0.000000,0.000000,1.767710e-07,0.250000
2,60000,MS_4951,MS_4951_POD_7,NODE_46562,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,8.249315e-07,455.847785
3,120000,MS_42505,MS_20844_POD_104,NODE_30733,0.000000,0.000000,32.523810,0.000000e+00,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
4,60000,MS_73317,MS_73317_POD_1797,NODE_3619,10.119451,0.000012,9.996974,7.169679e-12,0.0,0.0,...,0.000000,0.000000,0.969355,0.000006,0.00000,0.000000,24.421801,0.000002,0.000000e+00,0.000000

In [16]:
mcrrt.columns

Index(['timestamp', 'msname', 'msinstanceid', 'nodeid', 'providerrpc_rt',
       'providerrpc_mcr', 'consumerrpc_rt', 'consumerrpc_mcr', 'writemc_rt',
       'writemc_mcr', 'readmc_rt', 'readmc_mcr', 'writedb_rt', 'writedb_mcr',
       'readdb_rt', 'readdb_mcr', 'consumermq_rt', 'consumermq_mcr',
       'providermq_rt', 'providermq_mcr', 'http_mcr', 'http_rt'],
      dtype='str')

### Pre-Processing

### Columns of dataset
#### 1. Call_graph: 
Index(['timestamp', 'traceid', 'service', 'rpc_id', 'rpctype', 'um',
       'uminstanceid', 'interface', 'dm', 'dminstanceid', 'rt'],
      dtype='object')

#### 2. MS_Metric
Index(['timestamp', 'msname', 'msinstanceid', 'nodeid', 'cpu_utilization',
       'memory_utilization'],
      dtype='object')


#### 3. MCRRT 
Index(['timestamp', 'msname', 'msinstanceid', 'nodeid', 'providerrpc_rt',
       'providerrpc_mcr', 'consumerrpc_rt', 'consumerrpc_mcr', 'writemc_rt',
       'writemc_mcr', 'readmc_rt', 'readmc_mcr', 'writedb_rt', 'writedb_mcr',
       'readdb_rt', 'readdb_mcr', 'consumermq_rt', 'consumermq_mcr',
       'providermq_rt', 'providermq_mcr', 'http_mcr', 'http_rt'],
      dtype='object')

#### 4. Node Metric
Index(['timestamp', 'nodeid', 'cpu_utilization', 'memory_utilization'], dtype='object')

In [17]:
node_metric.columns

Index(['timestamp', 'nodeid', 'cpu_utilization', 'memory_utilization'], dtype='str')

In [18]:
callp['dm'].nunique()

17127

In [19]:
msmetric.head(5)

,timestamp,msname,msinstanceid,nodeid,cpu_utilization,memory_utilization
0,300000,MS_68185,MS_68185_POD_91,NODE_20236,0.172378,0.662361
1,420000,MS_25215,MS_25215_POD_372,NODE_36528,0.085708,0.432862
2,720000,MS_31285,MS_31285_POD_916,NODE_23966,0.445229,0.572093
3,780000,MS_42019,MS_42019_POD_38,NODE_34880,0.091057,0.529339
4,900000,MS_9482,MS_9482_POD_332,NODE_45529,0.177660,0.642626

In [20]:
mcrrt.head(5)

,timestamp,msname,msinstanceid,nodeid,providerrpc_rt,providerrpc_mcr,consumerrpc_rt,consumerrpc_mcr,writemc_rt,writemc_mcr,...,writedb_rt,writedb_mcr,readdb_rt,readdb_mcr,consumermq_rt,consumermq_mcr,providermq_rt,providermq_mcr,http_mcr,http_rt
0,60000,MS_49464,MS_49464_POD_4,NODE_41256,0.000000,0.000000,5.346655,0.000000e+00,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,4.96123,0.000155,1.344713,0.000071,1.865916e-07,0.083333
1,120000,MS_66860,MS_43316_POD_3,NODE_36486,6.257353,0.000001,0.000000,7.869866e-13,0.0,0.0,...,1.911765,0.000002,0.442857,0.000002,0.00000,0.000000,0.000000,0.000000,1.767710e-07,0.250000
2,60000,MS_4951,MS_4951_POD_7,NODE_46562,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,8.249315e-07,455.847785
3,120000,MS_42505,MS_20844_POD_104,NODE_30733,0.000000,0.000000,32.523810,0.000000e+00,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
4,60000,MS_73317,MS_73317_POD_1797,NODE_3619,10.119451,0.000012,9.996974,7.169679e-12,0.0,0.0,...,0.000000,0.000000,0.969355,0.000006,0.00000,0.000000,24.421801,0.000002,0.000000e+00,0.000000

#### Sample 350K file to build Model

In [44]:
sample_df = call_graph.sample(n=350000, random_state=42)

sample_df.to_csv("CallGraph_350k.csv", index=False)

print("✅ Random 350k dataset created")

✅ Random 350k dataset created

In [45]:
os.listdir()

['.git',
 '.~lock.batch_instance.csv#',
 'Alibaba_Data_Job_Level.csv',
 'Alibaba_Data_Task_Level.csv',
 'batch_instance.csv',
 'batch_task.csv',
 'CallGraph_0.csv',
 'CallGraph_350k.csv',
 'container_event.csv',
 'container_usage.csv',
 'MCRRTUpdate_0.csv',
 'MSMetricsUpdate_0.csv',
 'NodeMetricsUpdate_0.csv',
 'server_event.csv',
 'server_usage.csv',
 'SoCC2021.pdf',
 'ssp.ipynb']

#### Building rest of 350K based on Callgraph

In [21]:
call_sample = pd.read_csv('CallGraph_350k.csv')

In [22]:
call_sample.head(10)

,timestamp,traceid,service,rpc_id,rpctype,um,uminstanceid,interface,dm,dminstanceid,rt
0,76237,T_21388589380,S_115042431,0.1.3.27,mc,MS_48385,MS_48385_POD_3776,j9JPeZqdfa,MS_14728,UNKNOWN,0.0
1,104310,T_4767157225,S_104419129,0.1.2.15,mc,MS_4660,MS_4660_POD_2652,27LLHBLtvK,MS_46825,MS_46825_POD_289,1.0
2,35589,T_19429784845,S_58367703,0.1.1.6,mq,MS_19279,MS_19279_POD_91,hMOAwKKkMh,MS_30234,MS_30234_POD_76,0.0
3,80083,T_8925144016,S_80466277,0.1.1.2.1.56.1,mc,MS_51052,MS_51052_POD_2061,K7owOgUd1X,MS_66332,MS_66332_POD_40,0.0
4,44789,T_3037066685,S_104419129,0.1.2.5,mc,MS_4660,MS_4660_POD_1359,ScFx7XudDg,MS_55085,MS_55085_POD_700,0.0
5,119818,T_18910370216,S_156482560,0.1,http,UNKNOWN,UNAVAILABLE,bHiJXTZtx1,MS_40912,MS_40912_POD_303,2.0
6,47190,T_19194028381,S_51794709,0,http,USER,USER,Rs4VbRVJj2,MS_42200,MS_42200_POD_672,0.0
7,141995,T_10104064984,S_157704810,0.1.1.2.1.47,mc,MS_51052,MS_51052_POD_412,NbWtDAnQop,MS_24560,MS_24560_POD_1,0.0
8,113477,T_4005675566,S_84744291,0.1.2.7,mc,MS_20820,MS_20820_POD_289,CZYUPBqany,MS_37691,MS_37691_POD_3241,1.0
9,143478,T_18047655436,S_100293104,0.959,db,MS_36146,MS_36146_POD_9,mJxUT-THwr,MS_27421,UNKNOWN,0.0

##### Filtered Metrics File

In [ ]:
# Step 1: Get all unique instance IDs from CallGraph
um_instances = set(call_sample['uminstanceid'].dropna())
dm_instances = set(call_sample['dminstanceid'].dropna())

# Combine both
all_instances = um_instances.union(dm_instances)

print("Total unique instances from CallGraph:", len(all_instances))

# Step 2: Filter MSMetrics based on these instances
filtered_msmetrics = msmetric[
    msmetric['msinstanceid'].isin(all_instances)
]

# Step 3: Save new dataset
filtered_msmetrics.to_csv("Filtered_MSMetrics.csv", index=False)

print("✅ Filtered MSMetrics file created successfully")

Total unique instances from CallGraph: 149825
✅ Filtered MSMetrics file created successfully

In [52]:
# Step 1: Get all unique instance IDs from CallGraph
um_instances = set(call_sample['uminstanceid'].dropna())
dm_instances = set(call_sample['dminstanceid'].dropna())

# Combine both
all_instances = um_instances.union(dm_instances)

print("Total unique instances from CallGraph:", len(all_instances))

# Step 2: Filter MSMetrics based on these instances
filtered_mcrrt = mc_rrt[
    mc_rrt['msinstanceid'].isin(all_instances)
]

# Step 3: Save new dataset
filtered_mcrrt.to_csv("Filtered_mc_rrt.csv", index=False)

print("✅ Filtered MCRRT file created successfully")

Total unique instances from CallGraph: 149825
✅ Filtered MCRRT file created successfully

In [ ]:
filtered_msmetrics.head(5)

,timestamp,msname,msinstanceid,nodeid,providerrpc_rt,providerrpc_mcr,consumerrpc_rt,consumerrpc_mcr,writemc_rt,writemc_mcr,...,writedb_rt,writedb_mcr,readdb_rt,readdb_mcr,consumermq_rt,consumermq_mcr,providermq_rt,providermq_mcr,http_mcr,http_rt
87,60000,MS_32772,MS_32772_POD_2,NODE_9615,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.181818,1.080267e-07,0.000000,0.000000,0.000000e+00,0.000000
174,0,MS_73179,MS_73179_POD_22,NODE_1955,5.358554,0.000020,16.888889,1.200733e-11,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000
201,60000,MS_41068,MS_41068_POD_15,NODE_36877,23.815574,0.000017,58.387097,9.883626e-12,0.000000,0.000000,...,0.983157,0.000034,0.966334,0.000044,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000
253,0,MS_23174,MS_23174_POD_3,NODE_45340,19.618846,0.000023,11.298297,1.363339e-11,0.525123,0.000010,...,0.000000,0.000000,0.793103,0.000001,19.049180,2.995287e-06,1.513761,0.000001,1.669504e-07,0.222222
578,120000,MS_40586,MS_40586_POD_123,NODE_12749,5.051596,0.000356,9.009080,2.100618e-10,0.588530,0.000029,...,1.895911,0.000003,0.759735,0.000046,61.500000,1.964123e-08,2.892857,0.000001,0.000000e+00,0.000000

In [55]:
um_instances = set(filtered_msmetrics['nodeid'].dropna())
dm_instances = set(filtered_mcrrt['nodeid'].dropna())

# Combine both
all_instances = um_instances.union(dm_instances)

print("Total unique nodeid:", len(all_instances))

# Step 2: Filter MSMetrics based on these instances
filtered_nodemetric = node_metric[
    node_metric['nodeid'].isin(all_instances)
]

# Step 3: Save new dataset
filtered_nodemetric.to_csv("Filtered_NodeMetric.csv", index=False)

print("✅ Filtered NodeMetric file created successfully")

Total unique nodeid: 5102
✅ Filtered NodeMetric file created successfully

#### PRE-PROCESSING

In [23]:
call_sample.head(5)

,timestamp,traceid,service,rpc_id,rpctype,um,uminstanceid,interface,dm,dminstanceid,rt
0,76237,T_21388589380,S_115042431,0.1.3.27,mc,MS_48385,MS_48385_POD_3776,j9JPeZqdfa,MS_14728,UNKNOWN,0.0
1,104310,T_4767157225,S_104419129,0.1.2.15,mc,MS_4660,MS_4660_POD_2652,27LLHBLtvK,MS_46825,MS_46825_POD_289,1.0
2,35589,T_19429784845,S_58367703,0.1.1.6,mq,MS_19279,MS_19279_POD_91,hMOAwKKkMh,MS_30234,MS_30234_POD_76,0.0
3,80083,T_8925144016,S_80466277,0.1.1.2.1.56.1,mc,MS_51052,MS_51052_POD_2061,K7owOgUd1X,MS_66332,MS_66332_POD_40,0.0
4,44789,T_3037066685,S_104419129,0.1.2.5,mc,MS_4660,MS_4660_POD_1359,ScFx7XudDg,MS_55085,MS_55085_POD_700,0.0

In [24]:
len(call_sample['service'].unique())

21475

In [25]:
call_sample[call_sample['rpc_id'] == '0' ]

,timestamp,traceid,service,rpc_id,rpctype,um,uminstanceid,interface,dm,dminstanceid,rt
6,47190,T_19194028381,S_51794709,0,http,USER,USER,Rs4VbRVJj2,MS_42200,MS_42200_POD_672,0.0
11,3024,T_15276019308,S_32028218,0,rpc,USER,USER,KLH0K5XWXZ,MS_15600,MS_15600_POD_133,106.0
20,138948,T_3735163354,S_130831269,0,http,USER,USER,KFUG835JJw,MS_42200,MS_42200_POD_1218,0.0
32,177223,T_11926851329,S_148191226,0,http,USER,USER,SavWR7ho2O,MS_42200,MS_42200_POD_222,3.0
37,118539,T_4167671474,S_130831269,0,http,USER,USER,KFUG835JJw,MS_42200,MS_42200_POD_544,0.0
...,...,...,...,...,...,...,...,...,...,...,...
349852,76007,T_2430615901,S_1823467,0,http,USER,USER,MNU9Pso9u6,MS_50685,MS_50685_POD_8,0.0
349862,10708,T_13641980905,S_58367703,0,http,USER,USER,yAtIDpXMD6,UNKNOWN,UNKNOWN_POD_4343154,6.0
349895,71202,T_25200917822,S_151206381,0,http,USER,USER,gH-CarlM8A,MS_72966,MS_72966_POD_19,3.0
349903,82483,T_13038405705,S_98402027,0,http,USER,USER,CtB3iQgVJo,MS_37575,MS_37575_POD_86,10.0
349907,55301,T_12384285779,S_152366609,0,http,USER,USER,weldAbyWxW,UNKNOWN,UNKNOWN_POD_33096850,63.0

In [26]:
call_sample['service'].nunique()

21475

In [27]:
call_sample['traceid'].nunique()

247158

In [28]:
grouped_traces = call_sample.groupby('traceid')

In [29]:
with_user = call_sample.loc[call_sample['um'] == 'USER']['traceid'].unique()

In [30]:
with_user

<StringArray>
['T_19194028381', 'T_15276019308',  'T_3735163354', 'T_11926851329',
  'T_4167671474', 'T_19978653653', 'T_23366371414', 'T_24081171843',
 'T_10636034099', 'T_14849276262',
 ...
  'T_3591364014', 'T_15917573355', 'T_16967805398', 'T_14556849456',
 'T_10461937370',  'T_2430615901', 'T_13641980905', 'T_25200917822',
 'T_13038405705', 'T_12384285779']
Length: 27553, dtype: str

In [31]:
callgraph_withuser = call_sample[call_sample['traceid'].isin(with_user)].copy()

In [32]:
call_graph.loc[(call_graph['traceid'] == 'T_17745682026') ,['dm','rpc_id','rt']]

               dm      rpc_id    rt
1721524  MS_27421  0.11.1.5.1   0.0
1721525  MS_27421  0.10.1.6.3   0.0
1721526  MS_27421  0.10.1.6.1   0.0
1721527  MS_27421  0.11.1.5.3   0.0
1721528  MS_58340       0.9.1  25.0
...           ...         ...   ...
1721870  MS_59795   0.9.1.3.6   0.0
1721871  MS_59795   0.9.1.3.4   1.0
1721872  MS_59795   0.9.1.3.2   1.0
1721873  MS_59795  0.10.1.5.2   1.0
1721874  MS_59795  0.10.1.5.4   1.0

[131 rows x 3 columns]

In [33]:
call_graph.head(5)

,timestamp,traceid,service,rpc_id,rpctype,um,uminstanceid,interface,dm,dminstanceid,rt
0,115352,T_11560863075,S_153587416,0.1,rpc,MS_58845,MS_58845_POD_0,xOuy6-80Vt,MS_71712,MS_71712_POD_244,2.0
1,86450,T_22121589080,S_1798353,0.1,rpc,MS_24094,MS_24094_POD_3317,4Db39LxDTC,MS_24094,MS_24094_POD_5168,5.0
2,86450,T_22121589080,S_1798353,0.1,rpc,MS_24094,MS_24094_POD_983,4Db39LxDTC,MS_24094,MS_24094_POD_5168,5.0
3,155753,T_22121586395,S_85905920,0.1,rpc,MS_24094,MS_24094_POD_5463,1oNt-EK5Lm,MS_67455,MS_67455_POD_222,9.0
4,90649,T_22825688569,S_160146479,0.1.1.1,http,MS_29868,MS_29868_POD_22,XQrDXTN_dB,UNKNOWN,UNKNOWN,18.0

In [1]:
import networkx as nx
import matplotlib.pyplot as plt

# 1. Filter the data for your specific trace
trace_id = 'T_17745682026'
trace_data = call_graph[call_graph['traceid'] == trace_id]

# 2. Initialize a Directed Graph
G = nx.DiGraph()

# 3. Add nodes and edges
for _, row in trace_data.iterrows():
    caller = f"{row['um']}\n({row['rpc_id']})"
    callee = f"{row['dm']}\n({row['rpc_id']}.x)" # Visualizing the next hop
    
    # We use the service names as nodes and rpc_id to show the flow
    G.add_edge(row['um'], row['dm'], label=row['rpc_id'])

# 4. Use a Graphviz-style layout for a tree structure
plt.figure(figsize=(12, 8))
pos = nx.spring_layout(G) # Or use nx.nx_agraph.graphviz_layout(G, prog='dot') if installed

# 5. Draw the tree
nx.draw(G, pos, with_labels=True, node_size=3000, node_color="skyblue", 
        font_size=10, font_weight="bold", arrows=True, edge_color="gray")

# Add edge labels (RPC IDs)
edge_labels = nx.get_edge_attributes(G, 'label')
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels)

plt.title(f"Call Graph Tree for Trace: {trace_id}")
plt.show()

NameError: name 'call_graph' is not defined

In [126]:
callgraph_withuser['rpc_id'].nunique()

1330

In [35]:
call_graph['timestamp'].unique()

array([115352,  86450, 155753, ..., 144989,  14773, 104778],
      shape=(180000,))